export type ExamQuestion = { id: number; question: string; options: string[]; answer: number };

export const EXAM_QUESTIONS: ExamQuestion[] = [
  { id: 1, question: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyper Transfer Markup Language", "Home Tool Markup Language"], answer: 0 },
  { id: 2, question: "Which language is primarily used for styling web pages?", options: ["Python", "CSS", "SQL", "C++"], answer: 1 },
  { id: 3, question: "What does API stand for?", options: ["Application Programming Interface", "Automated Program Interaction", "Application Process Integration", "Advanced Programming Instruction"], answer: 0 },
  { id: 4, question: "Which of these is a JavaScript framework?", options: ["Django", "Laravel", "React", "Flask"], answer: 3 },
  { id: 5, question: "What does Git do?", options: ["Runs the browser", "Version control", "Designs logos", "Hosts databases only"], answer: 1 },
  { id: 6, question: "Which HTTP method is used to retrieve data?", options: ["POST", "DELETE", "GET", "PATCH"], answer: 2 },
  { id: 7, question: "What is the default port for HTTPS?", options: ["80", "443", "3000", "8080"], answer: 1 },
  { id: 8, question: "Which database is NoSQL?", options: ["MySQL", "PostgreSQL", "MongoDB", "SQLite"], answer: 2 },
  { id: 9, question: "What does CSS specificity determine?", options: ["Which style wins", "Page load speed", "Image size", "Font family only"], answer: 0 },
  { id: 10, question: "In React, what is useState used for?", options: ["Routing", "State management", "Styling", "Testing"], answer: 1 },
  { id: 11, question: "What does DNS do?", options: ["Encrypts passwords", "Translates domain to IP", "Compresses images", "Minifies JS"], answer: 1 },
  { id: 12, question: "Which is a valid JSON value?", options: ["undefined", "NaN", "null", "Infinity"], answer: 2 },
  { id: 13, question: "What is the time complexity of binary search?", options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"], answer: 1 },
  { id: 14, question: "Which tool is used to containerize apps?", options: ["Docker", "Figma", "Slack", "Notion"], answer: 0 },
  { id: 15, question: "What does JWT stand for?", options: ["Java Web Token", "JSON Web Token", "Joint Working Technique", "Just Waiting Time"], answer: 1 },
  { id: 16, question: "Which SQL clause filters rows?", options: ["ORDER BY", "WHERE", "GROUP BY", "HAVING"], answer: 1 },
  { id: 17, question: "What is the purpose of a CDN?", options: ["Store passwords", "Speed up content delivery", "Write code", "Manage emails"], answer: 1 },
  { id: 18, question: "In Git, which command creates a new branch?", options: ["git branch", "git clone", "git push", "git pull"], answer: 0 },
  { id: 19, question: "Which is NOT a HTTP status code class?", options: ["2xx Success", "3xx Redirect", "6xx Retry", "5xx Server Error"], answer: 2 },
  { id: 20, question: "What does UX stand for?", options: ["User Experience", "Ultimate Xpress", "Uniform Exchange", "User Extension"], answer: 0 },
  { id: 21, question: "Which language runs in the browser without compilation by default?", options: ["Python", "Java", "JavaScript", "C#"], answer: 2 },
  { id: 22, question: "What is the main use of Supabase?", options: ["Video editing", "Backend as a Service", "Graphic design", "Music streaming"], answer: 1 },
  { id: 23, question: "Which CSS unit is relative to viewport width?", options: ["px", "em", "vw", "cm"], answer: 2 },
  { id: 24, question: "What does Vercel primarily host?", options: ["Mobile games only", "Web applications", "Desktop OS", "Hardware drivers"], answer: 1 },
  { id: 25, question: "Which data structure is LIFO?", options: ["Queue", "Stack", "Tree", "Graph"], answer: 1 },
  { id: 26, question: "What does HTTPS add over HTTP?", options: ["Faster rendering", "Encryption (TLS)", "Smaller payload", "Better SEO only"], answer: 1 },
  { id: 27, question: "In Next.js, where do API routes live?", options: ["pages/api or app/api", "components/api", "public/api", "styles/api"], answer: 0 },
  { id: 28, question: "Which command installs dependencies with npm?", options: ["npm start", "npm install", "npm build", "npm test"], answer: 1 },
  { id: 29, question: "What is CORS?", options: ["A CSS framework", "Cross-Origin Resource Sharing", "A database engine", "A testing library"], answer: 1 },
  { id: 30, question: "Which key uniquely identifies a DB row?", options: ["Foreign key", "Primary key", "Index key", "Candidate"], answer: 1 },
  { id: 31, question: "What does Figma primarily do?", options: ["Host APIs", "UI design", "Compile code", "Run containers"], answer: 1 },
  { id: 32, question: "Which method prevents SQL injection best?", options: ["String concat", "Parameterized queries", "eval()", "innerHTML"], answer: 1 },
  { id: 33, question: "What is the purpose of .env files?", options: ["Store secrets/config", "Store images", "Define routes", "Cache pages"], answer: 0 },
  { id: 34, question: "Which is a valid React hook rule?", options: ["Call hooks inside loops", "Call hooks at top level only", "Call hooks inside conditions randomly", "Call hooks outside components"], answer: 1 },
  { id: 35, question: "What does RLS in Supabase mean?", options: ["Row Level Security", "Remote Load Service", "Rapid Link System", "Request Limit Service"], answer: 0 },
  { id: 36, question: "Which is NOT a JavaScript data type?", options: ["string", "boolean", "float", "symbol"], answer: 2 },
  { id: 37, question: "What is the output of typeof null in JS?", options: ['"null"', '"object"', '"undefined"', '"number"'], answer: 1 },
  { id: 38, question: "Which protocol is used for sending email?", options: ["FTP", "SMTP", "HTTP", "SSH"], answer: 1 },
  { id: 39, question: "What does Resend do?", options: ["Sends transactional email", "Edits video", "Manages DNS only", "Compiles TypeScript"], answer: 0 },
  { id: 40, question: "Which HTML tag is for the largest heading?", options: ["<h6>", "<h1>", "<header>", "<head>"], answer: 1 },
  { id: 41, question: "In CSS, what does display: none do?", options: ["Hides element completely", "Makes it transparent only", "Moves it off-screen only", "Disables clicks only"], answer: 0 },
  { id: 42, question: "What is hydration in Next.js?", options: ["Attaching JS to server HTML", "Uploading images", "Caching API", "Deploying to Vercel"], answer: 0 },
  { id: 43, question: "Which is a good password practice?", options: ["Reuse same password", "Use long unique passwords + 2FA", "Share via email", "Store in plaintext"], answer: 1 },
  { id: 44, question: "What does FIESU stand for at this TechFest?", options: ["Federation of Iyin-Ekiti Students Union", "Financial Institute", "Film Society", "Festival Crew"], answer: 0 },
  { id: 45, question: "What is the theme of Iyin-Ekiti TechFest?", options: ["Thinking Beyond Borders", "Code and Cook", "Build Fast", "Future Now"], answer: 0 },
  { id: 46, question: "Which is a correct way to handle secrets in production?", options: ["Commit to GitHub", "Use env vars / secret manager", "Hardcode in HTML", "Put in README"], answer: 1 },
  { id: 47, question: "What does npm stand for?", options: ["Node Package Manager", "New Project Maker", "Network Page Module", "Node Process Monitor"], answer: 0 },
  { id: 48, question: "Which array method transforms each element?", options: ["filter", "map", "reduce", "forEach only"], answer: 1 },
  { id: 49, question: "What is the benefit of versioning content (page_versions)?", options: ["Rollback to previous publish", "Faster internet", "Smaller images", "More followers"], answer: 0 },
  { id: 50, question: "If you exit the Exam Terminal, what happens?", options: ["Nothing", "You are disqualified", "Timer pauses", "Score doubles"], answer: 1 },
];
