export type ExamQuestion = { id: number; question: string; options: string[]; answer: number };

export const EXAM_QUESTIONS: ExamQuestion[] = [
  { id: 1, question: "What is the primary purpose of a variable in programming?", options: ["To repeat a program", "To store and reference data", "To delete files", "To compile code"], answer: 1 },
  { id: 2, question: "What is the output of this Python code? x = 5 y = 2 print(x + y * 3)", options: ["21", "11", "15", "7"], answer: 1 },
  { id: 3, question: "Which Java keyword is used to create a subclass from a class?", options: ["implements", "extends", "inherits", "super"], answer: 1 },
  { id: 4, question: "What does this JavaScript code return? console.log(typeof \"Hello\");", options: ["text", "String", "string", "char"], answer: 2 },
  { id: 5, question: "Which of these is a valid Boolean value in Python?", options: ["\"True\"", "TRUE", "True", "1True"], answer: 2 },
  { id: 6, question: "In C#, which keyword is commonly used to declare a constant whose value is fixed at compile time?", options: ["static", "const", "fixed", "readonly"], answer: 1 },
  { id: 7, question: "What is the output of this Go code? x := 10 x += 5 fmt.Println(x)", options: ["10", "5", "15", "Error"], answer: 2 },
  { id: 8, question: "Which Rust keyword declares a variable that cannot be reassigned by default?", options: ["var", "let", "mut", "constvar"], answer: 1 },
  { id: 9, question: "What is the output of this Java code? int x = 10; System.out.println(x % 3);", options: ["3", "1", "0", "10"], answer: 1 },
  { id: 10, question: "What does the return statement do in a function?", options: ["Repeats the function", "Ends the function and optionally sends a value back", "Deletes the function", "Starts a new loop"], answer: 1 },
  { id: 11, question: "Which data structure follows the Last In First Out principle?", options: ["Queue", "Stack", "Array", "Linked list"], answer: 1 },
  { id: 12, question: "What is the index of the first element in a standard Python list?", options: ["0", "1", "-1", "It depends on the list size"], answer: 0 },
  { id: 13, question: "Which data structure is most suitable for processing tasks in the order they arrive?", options: ["Stack", "Queue", "Tree", "Graph"], answer: 1 },
  { id: 14, question: "What is the time complexity of accessing an element by index in an array?", options: ["O(n)", "O(log n)", "O(1)", "O(n²)"], answer: 2 },
  { id: 15, question: "What is the main purpose of a sorting algorithm?", options: ["To remove all duplicate values", "To arrange elements in a specified order", "To compress a file", "To encrypt information"], answer: 1 },
  { id: 16, question: "Which algorithm is generally suitable for searching a sorted array efficiently?", options: ["Linear search", "Binary search", "Random search", "Depth first search"], answer: 1 },
  { id: 17, question: "What is the worst case time complexity of linear search in an array of n elements?", options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 2 },
  { id: 18, question: "What is the output of this Python code? numbers = [2, 4, 6] numbers.append(8) print(len(numbers))", options: ["3", "4", "5", "8"], answer: 1 },
  { id: 19, question: "Which data structure is commonly used to represent relationships between connected locations in a network?", options: ["Stack", "Graph", "Integer", "Boolean"], answer: 1 },
  { id: 20, question: "What is the main advantage of using a hash map or dictionary?", options: ["It always sorts data automatically", "It stores only numbers", "It supports efficient key based lookup on average", "It prevents all duplicate values"], answer: 2 },
  { id: 21, question: "What is encapsulation in object oriented programming?", options: ["Combining data and related methods while controlling access to internal state", "Repeating code several times", "Converting code into machine language", "Running several programs simultaneously"], answer: 0 },
  { id: 22, question: "Which concept allows a class to acquire properties and methods from another class?", options: ["Encapsulation", "Inheritance", "Compilation", "Iteration"], answer: 1 },
  { id: 23, question: "What is polymorphism?", options: ["The ability of an object or interface to support different implementations of an operation", "The ability to store only one variable", "The process of deleting objects", "The conversion of source code into comments"], answer: 0 },
  { id: 24, question: "In Java, which keyword refers to the current object?", options: ["super", "this", "self", "current"], answer: 1 },
  { id: 25, question: "What is the purpose of a constructor in a class?", options: ["To initialise an object when it is created", "To destroy every object in a program", "To repeat a loop", "To compile the entire application"], answer: 0 },
  { id: 26, question: "Which statement about interfaces is generally correct?", options: ["They can define a contract that implementing types must satisfy", "They can only store integers", "They always contain a program main function", "They prevent code reuse"], answer: 0 },
  { id: 27, question: "In Python, what does the self parameter conventionally represent in an instance method?", options: ["The parent class", "The current instance", "A global variable", "The Python interpreter"], answer: 1 },
  { id: 28, question: "What is method overriding?", options: ["Defining a compatible replacement implementation of an inherited method in a subclass", "Giving two variables the same value", "Calling a method repeatedly", "Deleting a method from memory"], answer: 0 },
  { id: 29, question: "What is the output of this JavaScript code? console.log(2 + \"3\");", options: ["5", "23", "NaN", "An error"], answer: 1 },
  { id: 30, question: "What is the output of this Python code? for i in range(3): print(i, end=\" \")", options: ["1 2 3", "0 1 2", "0 1 2 3", "3 2 1"], answer: 1 },
  { id: 31, question: "In Java, which collection type stores unique elements without duplicates?", options: ["ArrayList", "HashSet", "LinkedList", "StringBuilder"], answer: 1 },
  { id: 32, question: "What is the output of this C# code? int x = 4; Console.WriteLine(x * x);", options: ["8", "12", "16", "4"], answer: 2 },
  { id: 33, question: "What does mut allow in Rust?", options: ["A variable to be modified when otherwise it would be immutable", "A function to return two values automatically", "A program to skip compilation", "A variable to store only text"], answer: 0 },
  { id: 34, question: "In Go, which keyword declares a function?", options: ["func", "function", "def", "fn"], answer: 0 },
  { id: 35, question: "What is the output of this Python code? x = [1, 2, 3] print(x[-1])", options: ["1", "2", "3", "An error"], answer: 2 },
  { id: 36, question: "Which JavaScript operator checks strict equality without performing type conversion?", options: ["=", "==", "===", "!="], answer: 2 },
  { id: 37, question: "In Java, what is the usual purpose of the static keyword when applied to a method?", options: ["It makes the method belong to the class rather than a particular instance", "It prevents the method from executing", "It makes the method private automatically", "It converts the method into a constructor"], answer: 0 },
  { id: 38, question: "What does the Go defer statement do?", options: ["Schedules a function call to run when the surrounding function returns", "Immediately terminates the application", "Repeats the previous statement", "Prevents a function from returning"], answer: 0 },
  { id: 39, question: "In C#, what is the purpose of a try catch block?", options: ["To repeat code", "To handle exceptions", "To declare a class", "To sort a collection"], answer: 1 },
  { id: 40, question: "What is Rust ownership system primarily designed to help manage?", options: ["Variable naming conventions", "Memory safety and resource management", "Database table names", "User interface styling"], answer: 1 },
  { id: 41, question: "What is the output of this Python code? x = 1 while x < 4: x += 1 print(x)", options: ["3", "4", "5", "An infinite loop"], answer: 1 },
  { id: 42, question: "A function is supposed to return the larger of two numbers. Which implementation is correct in Python? def larger(a, b): return a if a > b else b", options: ["return a if a > b else b", "return a + b", "return a * b", "return a - b"], answer: 0 },
  { id: 43, question: "Your program crashes when a user enters text instead of a number. What is the best first step?", options: ["Ignore the error", "Validate the input and handle invalid values appropriately", "Delete the input feature", "Rewrite the entire application immediately"], answer: 1 },
  { id: 44, question: "What is debugging?", options: ["Designing a logo", "Finding and fixing errors in software", "Installing an operating system", "Writing documentation only"], answer: 1 },
  { id: 45, question: "What is the primary purpose of version control systems such as Git?", options: ["To track changes to files and support collaboration", "To guarantee that code has no bugs", "To replace all testing", "To automatically design user interfaces"], answer: 0 },
  { id: 46, question: "What is the main purpose of unit testing?", options: ["To test individual functions or components in isolation", "To test only the internet connection", "To replace all documentation", "To measure the popularity of an application"], answer: 0 },
  { id: 47, question: "Two developers modify the same codebase and Git reports a merge conflict. What should they do?", options: ["Delete the entire repository", "Resolve the conflicting changes and verify the result", "Ignore the conflict and assume Git will fix everything", "Uninstall Git"], answer: 1 },
  { id: 48, question: "An application works on the developer computer but fails on another computer. Which is a sensible first step?", options: ["Check dependencies, environment configuration, and error logs", "Assume the second computer is broken", "Delete the source code", "Remove all tests"], answer: 0 },
  { id: 49, question: "A team is building a solution for students who struggle to find affordable accommodation. What should they do FIRST?", options: ["Choose a programming language", "Understand the students needs and validate the problem", "Build every proposed feature immediately", "Design an elaborate logo"], answer: 1 },
  { id: 50, question: "A team has 24 hours to build a hackathon project. Which approach is most effective?", options: ["Spend the entire time discussing ideas", "Build as many unfinished features as possible", "Identify the core problem, build a working minimum viable product, test it, and prepare a demonstration", "Focus entirely on the presentation slides"], answer: 2 },
];
